name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the bug club! You've found your first issue - which means you're either extremely observant or you broke something. Either way, we're glad you're here! Thanks for taking the time to report this. We'll look into it once we can."
        pr-message: "Congratulations on your first pull request! 🎉 You've officially joined the ranks of people who fix problems instead of just complaining about them. We appreciate your contribution more than that one time someone brought donuts to the morning standup. We've been notified and will get back to you faster than you can say 'it works on my machine'!"
